spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop

springdoc:
  api-docs:
    path: "/api-docs"
  swagger-ui:
    showCommonExtensions: true